# Force Railway to use Python and run FastAPI from the src folder

[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmd = "pip install --no-cache-dir -r requirements.txt"


[start]
cmd = "uvicorn src.inference:app --host 0.0.0.0 --port $PORT"
